[versions]
agp = "8.2.2"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
lottie = "6.1.0"
shimmer = "0.5.0"
glide = "4.16.0"
circleImageView = "3.1.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

# UI/UX Libraries
lottie = { group = "com.airbnb.android", name = "lottie", version.ref = "lottie" }
shimmer = { group = "com.facebook.shimmer", name = "shimmer", version.ref = "shimmer" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glide" }
circleimageview = { group = "de.hdodenhof", name = "circleimageview", version.ref = "circleImageView" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

